# Define machine template
require conf/machine/zynq-generic.conf

# Including RFDC to build (not needed for zynq 7000 but do we need something else?)
# MACHINE_FEATURES:append = " rfsoc"

# Additional configurations
